name: dtube_togo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1

  # CRYPTO
  pointycastle: ^3.1.1
  crypto_keys: ^0.3.0
  bs58check: ^1.0.2
  bs58: ^1.0.1
  secp256k1: ^0.3.0
  hex: ^0.2.0
  elliptic: ^0.3.1
  ecdsa: ^0.0.2

  # UI - video related
  webview_flutter: ^2.0.8
  video_player: ^2.1.4
  youtube_explode_dart: ^1.9.6 #loading youtube metadata
  better_player: ^0.0.72 # player for ipfs/sia/local files
  youtube_plyr_iframe: ^2.0.6 # player for youtube

  # UI - markdown related
  flutter_markdown: ^0.6.2  # display markdown (only post description for now)
  url_launcher: ^6.0.4 

  # UI - image/video related
  #camera: ^0.8.1+3 # gives possibility to capture camera input in own widget
  image_picker: ^0.8.1+3 # open file browser / record image/video

  # UI - specific elements related
  
  font_awesome_flutter: ^9.0.0
  rflutter_alert: ^2.0.2
  flutter_speed_dial: ^4.1.0
  persistent_bottom_nav_bar: ^4.0.2
  another_flushbar: ^1.10.23
  loadmore: ^2.0.1
  jiffy: ^4.1.0 # library to display time in a user friendly way
  # scroll_snap_list: ^0.8.1 # not needed for now (snapping lists like instagram explore page)
  share_plus: ^2.1.4 # share post
    
  # NETWORK - cache related
  cached_network_image: ^3.0.0
  
  # NETWORK - http related
  http: ^0.13.3
  dio: ^4.0.0
  
  # OTHERS - global stuff
  flutter_phoenix: ^1.0.0 # for restarting the app on purpose (e.g. logout)
  flutter_launcher_icons: ^0.9.0 # creating app icons

  

# unsorted
  flutter_bloc: ^7.0.1
  equatable: ^2.0.2
  disk_space: ^0.1.1
  flutter_secure_storage: ^4.2.0
  intl: ^0.17.0
  video_compress: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # integration_test:
  #   sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/dtube_logo_white.png
    - assets/images/Flag_of_None.svg.png
    - assets/images/Image_of_none.svg.png
    - assets/images/appicon.png